dist: xenial
language: python
python:
  - 3.6
addons:
  postgresql: "9.6"

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE seared_quail;" -U postgres

script:
  - cd seared_quail
  - python manage.py migrate
  - coverage run ./manage.py test

after_success:
  - bash <(curl -s https://codecov.io/bash)
