dist: xenial
language: python
python:
  - 3.8
addons:
  postgresql: "9.6"

before_install:
  - pip install poetry
install:
  - poetry install

before_script:
  - psql -c "CREATE DATABASE seared_quail;" -U postgres
  - cp .env-sample .env

script:
  - poetry run pyupgrade --py37-plus $(find . -name '*.py')
  - poetry run black . --check
  - poetry run python manage.py makemigrations --check  # validate no outstanding model changes
  - poetry run python manage.py migrate
  - poetry run coverage run ./manage.py test

after_success:
  - bash <(curl -s https://codecov.io/bash)
