sudo: false
language: python
python:
  - 2.7

services: postgresql

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE seared_quail;" -U postgres

script:
  - cd seared_quail
  - python manage.py migrate
  - coverage run ./manage.py test

after_success:
  - ls -al
  - bash <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/a443c9f7c3ab4c336d10f1b5812e7ac7a979ebf3/codecov)
  - ls -al
