# Generated by Django 2.1.15 on 2020-04-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0009_auto_20160829_0624"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, editable=False, verbose_name="order"
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="description",
            field=models.TextField(blank=True, help_text="Enter valid HTML", null=True),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="img",
            field=models.ImageField(
                blank=True, null=True, upload_to="img/menuitem", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, editable=False, verbose_name="order"
            ),
        ),
    ]
